### ISSUE TITLE
Publish on docker hub

### ISSUE THREAD

**Issue by jeremyVignelles** [dprandzioch/docker-ddns#1]
Hi,
This project looks great!
Would you mind publish it on docker hub so that we can do `docker pull dprandzioch/docker-ddns:latest` and automatically get the updates?

**Comment by dstapp** [comment]
Hi, thanks for your Feedback! I was also already thinking about this but didn't find time to do it. I would need to update the readme and would also like to incorporate a CI service to build and push the image when changes occur.

This seems to be a good starting point: https://bhavik.io/2016/08/20/travis-ci-docker-image.html

As soon as I find time for it, I will do it! This issue will be kept open until it's done :-)

**Comment by vukasin-nikodijevic** [comment]
This is really good implementation for self hosted ddns - all I need for my project. It would be really nice to have it on Docker Hub.

Good work @dprandzioch 👍

**Comment by dstapp** [comment]
Thanks for the feedback. I just pushed the image to DockerHub and added instructions there on how to use it. From my first test this looks OK, but I'd like to have someone else testing this and give me some feedback to ensure that everything works.

Then I'll add the instructions to `README.md`.

Here's the link: https://hub.docker.com/r/davd/docker-ddns/

Regarding my post from before, I'll create a seperate issue later on for adding CI.

**Comment by jeremyVignelles** [comment]
Thanks a lot, I am setting a reminder to give it a try in the next two weeks. feel free to ask me again if you do not have any feedback after that.

**Comment by dstapp** [comment]
@jeremyVignelles Super :-) Thank you!

**Comment by jeremyVignelles** [comment]
Can confirm it works, with the following steps:

NOTE: I am using https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion . Commands should be the same except `docker run` where `-e` options are useless and you need to publish the 8080 port.

1. Create a folder to persist dynamic dns configuration across container restarts/image updates: for example : `/ddns`

2. Create the `/ddns/envfile` file with the correct content as in the tutorial. for this example, the ZONE will be `ddns.example.com`

3. Start the container:
```
docker run -d \
    --name ddns \
    --restart=always \
    -p 53:53 \
    -p 53:53/udp \
    --env-file /ddns/envfile \
    -v /ddns/data:/var/cache/bind \
    -e "VIRTUAL_HOST=ddns.example.com" \
    -e "VIRTUAL_PORT=8080" \
    -e "LETSENCRYPT_HOST=ddns.example.com" \
    -e "LETSENCRYPT_EMAIL=yourmail@gmail.com" \
    davd/docker-ddns
```

4. I had issues updating the ddns configuration, ( "NOTAUTH" errors, and then "SERVFAIL" errors). I had to run the following on the docker host (as root):

```
chmod a+w /ddns/*
```

5. Try it and enjoy

```
curl https://ddns.example.com/update?secret=<your-secret-key>&domain=<subdomain>&addr=<w.x.y.z>
```

**Comment by vukasin-nikodijevic** [comment]
@jeremyVignelles thanks for effort. 
I'll test it later today.

**Comment by dstapp** [comment]
@jeremyVignelles Thanks for your feedback! I will extend my documentation in README.md later and merge it to master then.

I'll leave this issue open until then.

**Comment by dstapp** [comment]
Documentation added. Thanks again @jeremyVignelles for adding insights on the problems you had. I've also explained this in the README.md now and hope people will be able to set it up using the provided information. Otherwise, anyone, feel free to add a issue, then we'll have to improve documentation ;-)
