### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by pwalter** [dprandzioch/docker-ddns#12]
Hi there,

I have a problem updating the dns record using the following url:
http://example.tld:8080/update?secret=changeme&domain=foo&addr=1.2.3.4

I only get the results:

**HTTP-GET Response**
{"Success":false,"Message":"exit status 2: update failed: NOTAUTH\n","Domain":"foo","Address":"1.2.3.4","AddrType":"A"}

**Server-Log shows only (no following messages):**
2018/02/19 17:08:07 A record update request: foo -> 1.2.3.4

Regards

**Comment by dstapp** [comment]
Hey, sorry for the late response. Do you run the application within Docker or with your own nameserver? Can you provide your config?

**Comment by dstapp** [comment]
I'm having this error myself now in production. I'll have a look how to fix it.

EDIT: I don't have it in my test setup but only in production Oo
Turns out I use persistent volumes in production and permissons for /var/cache/bind seem to be broken. I will push a fix to develop to see if this helps.

**Comment by dstapp** [comment]
@pwalter Do you use a persistent volume for /var/cache/bind ?
Try removing it and let me know if it worked

**Comment by dstapp** [comment]
@pwalter try using the `davd/docker-ddns:develop` image to see if this problem is fixed.

**Comment by dstapp** [comment]
@pwalter This is already released by now. Did you check again if this works?

**Comment by dstapp** [comment]
I'll close this issue since there's nothing left to do. If you have any further problems, please file a new bug.
