### ISSUE TITLE
Make Deploy error

### ISSUE THREAD

**Issue by hokleng** [dprandzioch/docker-ddns#17]
Helllo, 

I got this error when i issue command make deploy: 
---------------------------------------------------------
![image](https://user-images.githubusercontent.com/35158325/39044680-1b8b4de0-44bb-11e8-9c86-eee623923c66.png)
---------------------------------------------------------

**Comment by dstapp** [comment]
@hokleng Which Docker version are you running? I’m using multistage builds which is only supported from Docker 17.05.

**Comment by hokleng** [comment]
It is okay after i upgrade it.
Thanks
