### ISSUE TITLE
Persist state using docker volumes

### ISSUE THREAD

**Issue by jowi24** [dprandzioch/docker-ddns#19]
Can I persist current state (dyndns hostnames and ip data) using docker volumes? Currently, I'm loosing this information when I restart the container.

**Comment by jowi24** [comment]
Solved it by adding

`
    volumes:
      - data:/var/cache/bind
`

to the compose file.

**Comment by dstapp** [comment]
Yep this is the way to go, also shown here: https://github.com/dprandzioch/docker-ddns/blob/master/docker-compose.yml

But I think it should be documented in the README file, I'll do that.

**Comment by jowi24** [comment]
Aah, thank you. Haven't seen the docker-compose example...

**Comment by dstapp** [comment]
Added more documentation on develop.
