### ISSUE TITLE
Make deploy issue

### ISSUE THREAD

**Issue by DaveDischord** [dprandzioch/docker-ddns#2]
~/docker-ddns$ make deploy
docker build -t davd/dyndns-server .
make: docker: Command not found
Makefile:2: recipe for target 'image' failed
make: *** [image] Error 127

I get this on both Ubuntu Server 16 32- and 64-bit after update/upgrade.

Am I missing something?

**Comment by dstapp** [comment]
Hey, seems you don't have the "docker" binary in your $PATH. What does "which docker" return?
