### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by tracker1** [dprandzioch/docker-ddns#27]
Should probably consider integrating Let's Encrypt support into the web/update server, this way you can send updates over HTTPS so they cannot be intercepted.

**Comment by sscholl** [comment]
You should use a reverse proxy instead. Please take a look at traefik. If you need help, I can send you my setup.

**Comment by dstapp** [comment]
Hey, yeah I'd also go with a reverse proxy in front of docker-ddns to not increase it's complexity for stuff that can be offloaded. Traefik is a great choice alongside Caddy or nginx.

I'll close this for now but if you need any help, just let me know.
