### ISSUE TITLE
Update Docker Hub image

### ISSUE THREAD

**Issue by stv0g** [dprandzioch/docker-ddns#31]

**Comment by stv0g** [comment]
The existing image does not handle #29

**Comment by dstapp** [comment]
To be honest, I don’t get why it does not work with the old image but rebuilding it solves it - but apparently it does, at least for me. Do you have any further insights here? Was this a BIND bug that was solved with a newer version?

**Comment by dstapp** [comment]
Ah nevermind, just found the change sets. On the release build it does not work but the fix is already on develop. I will push a newer release in the next days to have this fix on master and :latest as well.

**Comment by stv0g** [comment]
Thanks 👍

**Comment by dstapp** [comment]
Release 1.3.0 just started building on DockerHub. Please let me know if everything works fine for you now.

**Comment by stv0g** [comment]
Works! 👍
