### ISSUE TITLE
Reverse search

### ISSUE THREAD

**Issue by FredyR4zox** [dprandzioch/docker-ddns#38]
I can't reverse search on the server :/
Is it normal? I'm using a VPN and all IP addresses on the DNS are from the VPN.

Commands:
nslookup
> server 127.0.0.1
> host 192.168.255.18

**Comment by dstapp** [comment]
Not sure if this works like that at all. The reverse lookup of {ip}.in-addr.arpa is set up on the IP provider side, isn't it?
