### ISSUE TITLE
can i set up forwarders?

### ISSUE THREAD

**Issue by jayntguru** [dprandzioch/docker-ddns#8]
I want to use this as a full lab DNS server but I need to be able to use forwarders as well. Can this work?

**Comment by dstapp** [comment]
Hey! Sorry, this is currently not possible. You could customize the bind configuration and then mount it to the container to make this work but note that then you'll have to keep track with upstream changes for that file manually.

**Comment by dstapp** [comment]
I'm closing this as there's nothing to do for now.
