### ISSUE TITLE
Handle invalid parameters gracefully

### ISSUE THREAD

**Issue by gw0** [dprandzioch/docker-ddns#9]
Missing or invalid parameters (like missing `addr=`) should not constantly trigger an index out-of-bounds exception.

**Comment by dstapp** [comment]
Hey, thanks for reporting. I just fixed this on develop and will test and merge it afterwards.

**Comment by dstapp** [comment]
Should be fixed now. 1.1.0 images are just building on DockerHub. Please let me know if you have any further issues.
